### ISSUE TITLE
Invalid fields added to built-in Intents

### ISSUE THREAD

**Issue by omenocal** [mediarain/voxa-cli#3]
When generating the languageModels, the field `slots` is added to built-in intents like:
```
{
  "name": "AMAZON.ScrollRightIntent",
  "samples": [],
  "slots": []
},
{
  "name": "AMAZON.PageUpIntent",
  "samples": [],
  "slots": []
},
{
  "name": "AMAZON.PageDownIntent",
  "samples": [],
  "slots": []
},
{
  "name": "AMAZON.MoreIntent",
  "samples": [],
  "slots": []
}
```

The Dev portal fixes this issue but we shouldn't generate invalid outputs

**Comment by rmberrios** [comment]
I'll close this issue. Because according to the documentation it shouldn't harm the language model.
