### ISSUE TITLE
Access user's location (Google Action)

### ISSUE THREAD

**Issue by BruceLampson** [mediarain/voxa-cli#8]
We're currently working on implementing a PermissionsRequest in order to determine a departure location. We would like to be able to ask permission to the user to access his location.

**Comment by rmberrios** [comment]
i don't think that feature is in dialogFlow. remember voxa-cli only exports dialogFlowAgents. I think this is set through the dialogConsole which we do not automate. @BruceLampson

**Comment by omenocal** [comment]
Agree with @rmberrios, and if you want this feature in your Alexa skill, you just need to enable the device permission in the skill configuration, send a card programmatically asking for the permission in the conversation, and if user granted you with the permission, you just need to hit the endpoint to get the device information. Take a look at this link for further explanation:

https://developer.amazon.com/docs/custom-skills/device-address-api.html

**Comment by rmberrios** [comment]
I will close this issue. In case you want to check how is in Alexa, i think vaseline-skill is a good example.

**Comment by omenocal** [comment]
We don't use the device address API. What we do use in vaseline are the List and Notifications APIs

**Comment by rmberrios** [comment]
But it behave the same, right? @omenocal

**Comment by omenocal** [comment]
Yes, same flow I explained, but with different permission string and endpoint to get the info

**Comment by BruceLampson** [comment]
Sorry guys, I been working with voxa-cli but I meant to add this issue to Vox repository instead.
